import { useState, useEffect } from "react";
import Layout from "@/components/layout/Layout";
import ChatInterface from "@/components/chat/ChatInterface";
import ChatHistorySidebar from "@/components/chat/ChatHistorySidebar";
import { useAuth } from "@/contexts/AuthContext";
import { useProjectContext } from "@/contexts/ProjectContext";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { api } from "@/lib/api";
import { Trash2, AlertTriangle } from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

const ChatPage = () => {
  const { user } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const [currentSessionId, setCurrentSessionId] = useState<string | null>(
    searchParams.get("session")
  );
  const projectId = searchParams.get("project");
  const { createProject, updateProject } = useProjectContext();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const navigate = useNavigate();

  // Sync URL with session ID
  useEffect(() => {
    if (currentSessionId) {
      setSearchParams({ session: currentSessionId });
    } else {
      setSearchParams({});
    }
  }, [currentSessionId, setSearchParams]);

  const handleSelectSession = (sessionId: string) => {
    setCurrentSessionId(sessionId);
  };

  const handleNewSession = () => {
    setCurrentSessionId(null);
  };

  const handleSessionCreated = (sessionId: string) => {
    setCurrentSessionId(sessionId);
  };

  const handleDeleteCurrentSession = async () => {
    if (!currentSessionId) return;

    try {
      await api.delete(`/chat/sessions/${currentSessionId}`);
      toast({ title: "SESSION_PURGED", description: "NEURAL_REGISTRY_CLEARED" });
      handleNewSession();
    } catch (error) {
      console.error("Failed to delete session:", error);
      toast({ title: "PURGE_FAILURE", description: "UNABLE_TO_CLEAN_NEURAL_LINK", variant: "destructive" });
    }
  };

  const handlePlanComplete = async (plan: any) => {
    try {
      if (projectId) {
        // Update existing project
        await updateProject(projectId, {
          planningDoc: {
            ...plan,
            id: `plan-${projectId}`,
            projectId,
            createdAt: new Date(),
          },
          status: "planning",
        });
        toast({ title: "PLAN_UPDATED", description: "PROJECT_METRICS_SYNCED" });
      } else {
        // Create new project from plan
        const newProject = await createProject(
          plan.name || "New AI Project",
          plan.description || "Generated by AI planner",
          (plan.category as any) || "other",
          plan.tags || []
        );

        if (newProject) {
          await updateProject(newProject.id, {
            planningDoc: {
              ...plan,
              id: `plan-${newProject.id}`,
              projectId: newProject.id,
              createdAt: new Date(),
            },
          });
          toast({ title: "PROJECT_INITIALIZED", description: `NODE_${newProject.name}_ACTIVE` });
          navigate(`/chat?session=${currentSessionId}&project=${newProject.id}`);
        }
      }
    } catch (error) {
      console.error("Failed to save plan:", error);
      toast({ title: "PERSISTENCE_FAILURE", description: "BUFFER_OVERFLOW_ON_SAVE", variant: "destructive" });
    }
  };

  if (!user) {
    return (
      <Layout>
        <div className="container max-w-4xl mx-auto py-32 text-center space-y-8 px-4">
          <div className="inline-flex items-center justify-center p-6 border-2 border-dashed border-primary/20 bg-primary/5 rounded-full mb-4">
            <div className="h-12 w-12 border-4 border-primary border-t-transparent rounded-full animate-spin" />
          </div>
          <h1 className="text-4xl font-black uppercase tracking-tighter">Access_Restricted</h1>
          <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-[0.4em]">AUTHENTICATION_LOG_REQUIRED_FOR_PLANNER_ACCESS</p>
          <Button asChild className="h-12 px-12 bg-primary hover:bg-primary/90 text-[10px] font-black uppercase tracking-[0.3em] rounded-none shadow-[0_4px_20px_rgba(var(--primary-rgb),0.2)]">
            <Link to="/login">Initialize_Login_Protocol</Link>
          </Button>
        </div>
      </Layout>
    );
  }

  return (
    <Layout hideFooter fullWidth>
      <div className="flex h-[calc(100vh-4rem)] bg-background relative overflow-hidden">
        {/* Technical Grid Overlay */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#primary33_1px,transparent_1px),linear-gradient(to_bottom,#primary33_1px,transparent_1px)] bg-[size:40px_40px] opacity-[0.03] pointer-events-none" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0%,rgba(0,0,0,0.4)_100%)] pointer-events-none" />

        {/* Mobile Sidebar Toggle - Matching PCB Style */}
        <Button
          variant="ghost"
          size="sm"
          className="lg:hidden fixed top-20 left-4 z-50 bg-neutral-900 border border-primary/20 text-[9px] font-black uppercase tracking-[0.2em] rounded-none h-9 px-4"
          onClick={() => setSidebarOpen(!sidebarOpen)}
        >
          {sidebarOpen ? "TERMINATE_HISTORY" : "RETRIEVE_REGISTRY"}
        </Button>

        {/* Sidebar - Matching PCB Style */}
        <div
          className={`${sidebarOpen ? "translate-x-0" : "-translate-x-full"
            } lg:translate-x-0 transition-transform duration-500 fixed lg:relative z-40 h-full border-r border-primary/10 bg-black/40 backdrop-blur-xl w-80 shrink-0`}
        >
          <div className="absolute inset-0 opacity-[0.02] bg-[repeating-linear-gradient(45deg,transparent,transparent_2px,var(--primary)_2px,var(--primary)_3px)] pointer-events-none" />
          <ChatHistorySidebar
            currentSessionId={currentSessionId}
            onSelectSession={handleSelectSession}
            onNewSession={handleNewSession}
          />
        </div>

        {/* Overlay for mobile */}
        {sidebarOpen && (
          <div
            className="lg:hidden fixed inset-0 bg-black/80 backdrop-blur-sm z-30"
            onClick={() => setSidebarOpen(false)}
          />
        )}

        {/* Chat Area - Main Workspace Style */}
        <div className="flex-1 flex flex-col relative z-10">
          {/* Workspace Status Bar */}
          <div className="h-12 border-b border-primary/10 bg-primary/[0.02] flex items-center justify-between px-6 shrink-0">
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse" />
                <span className="text-[10px] font-black uppercase tracking-widest text-primary/80">Neural_Link_Workspace</span>
              </div>
              <div className="h-4 w-px bg-primary/10" />
              <span className="text-[9px] font-mono font-bold text-muted-foreground/40 uppercase tracking-widest">
                SESSION_ID: {currentSessionId?.substring(0, 12).toUpperCase() || "AWAITING_INIT"}
              </span>
            </div>
            <div className="flex items-center gap-6">
              {currentSessionId && (
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 px-3 text-red-500 hover:text-red-400 hover:bg-red-500/10 text-[9px] font-black uppercase tracking-[0.2em] gap-2"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                      PURGE_SESSION
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent className="bg-neutral-900 border-primary/20">
                    <AlertDialogHeader>
                      <AlertDialogTitle className="text-primary uppercase tracking-tighter flex items-center gap-2">
                        <AlertTriangle className="w-5 h-5 text-red-500" />
                        Confirm_Purge_Protocol
                      </AlertDialogTitle>
                      <AlertDialogDescription className="text-muted-foreground text-xs uppercase tracking-widest leading-relaxed">
                        This will permanently erase all neural logs for session: {currentSessionId}. This action is irreversible once committed.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel className="bg-transparent border-primary/20 text-xs font-bold uppercase tracking-widest text-muted-foreground rounded-none">Cancel_Abort</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={handleDeleteCurrentSession}
                        className="bg-red-600 hover:bg-red-700 text-white text-xs font-black uppercase tracking-widest rounded-none shadow-[0_0_20px_rgba(220,38,38,0.3)]"
                      >
                        Confirm_Erase
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              )}
              <div className="flex items-center gap-2 border-l border-primary/10 pl-6 h-12">
                <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">LINK_QUALITY</span>
                <span className="text-[10px] font-mono font-bold text-success uppercase">EXCELLENT</span>
              </div>
            </div>
          </div>

          <ChatInterface
            sessionId={currentSessionId}
            projectId={projectId}
            onSessionCreated={handleSessionCreated}
            onPlanComplete={handlePlanComplete}
            onGeneratePCB={() => {
              if (projectId) navigate(`/pcb?project=${projectId}`);
              else toast({ title: "METRIC_ABORT", description: "SAVE_PLAN_BUFFER_BEFORE_SYNTHESIS" });
            }}
          />

          {/* Corner Decorations */}
          <div className="absolute top-16 left-4 w-4 h-4 border-l border-t border-primary/20 pointer-events-none" />
          <div className="absolute top-16 right-4 w-4 h-4 border-r border-t border-primary/20 pointer-events-none" />
          <div className="absolute bottom-4 left-4 w-4 h-4 border-l border-b border-primary/20 pointer-events-none" />
          <div className="absolute bottom-4 right-4 w-4 h-4 border-r border-b border-primary/20 pointer-events-none" />
        </div>
      </div>
    </Layout>
  );
};

export default ChatPage;
